ALTER TABLE questions ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS primary_keyword TEXT;
